# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Aiswarya Vinod Kumar 
tagline:          graduate student
description:      'passionate about learning.'
url:              http://aiskumo.github.io
baseurl:          /hyde/

author:
  name:           'Aiswarya Vinod Kumar'
  url:            http://aiskumo.github.io/hyde/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aiskumo
